imports:
    - php
filter:
    paths: [src/*]
tools:
    php_code_coverage: true
    php_sim:
        min_mass: 30 # Defaults to 16
build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'php phpunit.phar --coverage-clover=coverage.xml tests'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
    dependencies:
        before:
            - wget https://phar.phpunit.de/phpunit.phar
            - composer install --prefer-source
