imports:
    - php
filter:
    paths: [src/*]
tools:
    php_code_coverage: true
    php_sim:
        min_mass: 30 # Defaults to 16
build:
    environment:
        php:
            version: 7.3
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: 'php phpunit.phar --coverage-clover=coverage.xml tests'
                        coverage:
                            file: 'coverage.xml'
                            format: 'php-clover'
    dependencies:
        before:
            - wget -O phpunit.phar https://phar.phpunit.de/phpunit-6.phar
            - composer install --prefer-source

